### ISSUE TITLE
Installation on Raspberry Pi

### ISSUE THREAD

**Issue by EugeniaYao** [jrising/pysoundtouch#3]
Hi! I tried to use this wrapper on Raspbian, but it reported
`g++:error:unrecognized command line option "-msse2" `
Is it a problem of the version of gcc or the compiler? And I found that all of x86 is unsupported on ARM, not just SSE, which probably caused the error. Should I install an ARM toolchain to cross-compile the program? Any advice? Thanks!

**Comment by jrising** [comment]
You might not need the SSE instructions, since we're compiling with integer samples.  I would try removing the -msse2 argument.  These's actually a section of the SoundTouch readme that addresses this:

**2.2.4 Compiler issues with non-x86 processors**

SoundTouch library works also on non-x86 processors.

However, in case that you get compiler errors when trying to compile for non-Intel processor, edit the file "source\SoundTouch\Makefile.am" and remove the "-msse2" flag on the AM_CXXFLAGS line:

```
AM_CXXFLAGS=-O3 -fcheck-new -I../../include    # Note: -msse2 flag removed!
```
After that, run "./bootstrap" script, and then run configure and make again.
